/* PROCÉDURES — FORAGE AU DIAMANT (famille distincte, reliées aux PDF officiels). */
(window.PROCEDURES = window.PROCEDURES || []).push.apply(window.PROCEDURES, [
 {
  "id": "pro-dd-st-001",
  "code": "PRO-DD-ST-001",
  "titre": "Commencement d'un trou de forage avec un core barrel de 1,5 m",
  "categorie": "Forage",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour commencer un trou de forage avec un core barrel de 1,5 m",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour commencer un trou de forage avec un core barrel de 1,5 m",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2019",
  "date_revision": "",
  "source_pdf": "PRO-DD-ST-001",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-002",
  "code": "PRO-DD-ST-002",
  "titre": "Vider le tube carottier",
  "categorie": "Carottage & tube",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour vider le tube carottier.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour vider le tube carottier.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2019",
  "date_revision": "",
  "source_pdf": "PRO-DD-ST-002",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-003",
  "code": "PRO-DD-ST-003",
  "titre": "Fabrication d'un plancher pour foreuse aux diamants sous terre",
  "categorie": "Installation & plancher",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour la fabrication d’un plancher pour foreuse aux diamants sous terre",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour la fabrication d’un plancher pour foreuse aux diamants sous terre",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2019",
  "date_revision": "",
  "source_pdf": "PRO-DD-ST-003",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-004",
  "code": "PRO-DD-ST-004",
  "titre": "Récupération de tube carottier avec le loading chamber",
  "categorie": "Carottage & tube",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour extraire un tube carottier avec le loading chamber",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour extraire un tube carottier avec le loading chamber",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "octobre 2020",
  "date_revision": "",
  "source_pdf": "PRO-DD-ST-004",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-006",
  "code": "PRO-DD-ST-006",
  "titre": "Récupération du tube carottier avec un overshot de surface",
  "categorie": "Carottage & tube",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour la récupération du tube carottier avec un over shot de surface",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour la récupération du tube carottier avec un over shot de surface",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "",
  "date_revision": "",
  "source_pdf": "PRO-DD-ST-006",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-007",
  "code": "PRO-DD-ST-007",
  "titre": "Cimentation des trous de forage aux diamants (pompe 435)",
  "categorie": "Cimentation",
  "machines": [
   "Foreuse au diamant",
   "Pompe 435"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour l’utilisation de la pompe 435 lors des travaux de cimentation",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour l’utilisation de la pompe 435 lors des travaux de cimentation",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2019",
  "date_revision": "Mars 2025",
  "source_pdf": "PRO-DD-ST-007",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-008",
  "code": "PRO-DD-ST-008",
  "titre": "Installation du support de tiges de forage",
  "categorie": "Installation & plancher",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour l’installation du support de tige et en établir l’emplacement adéquat selon la configuration de la foreuse.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour l’installation du support de tige et en établir l’emplacement adéquat selon la configuration de la foreuse.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2021",
  "date_revision": "Août 2024",
  "source_pdf": "PRO-DD-ST-008",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-009-1",
  "code": "PRO-DD-ST-009-1",
  "titre": "Forage de trous ascendants de plus de 20° — STM-1500 / DR-600 #2907",
  "categorie": "Forage",
  "machines": [
   "STM-1500",
   "DR-600"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour le forage de trous ascendants de plus de 20 degrés. Elle donne des pistes de réflexion pour toutes les tâches ainsi que les risques entourant le forage ascendant.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour le forage de trous ascendants de plus de 20 degrés. Elle donne des pistes de réflexion pour toutes les tâches ainsi que les risques entourant le forage ascendant.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Juin 2021",
  "date_revision": "Avril 2023",
  "source_pdf": "PRO-DD-ST-009-1",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-009-2",
  "code": "PRO-DD-ST-009-2",
  "titre": "Forage de trous ascendants de plus de 20° — DR-600 #2923",
  "categorie": "Forage",
  "machines": [
   "DR-600"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour le forage de trous ascendants de plus de 20 degrés avec la DR-600 #2923. Elle donne des pistes de réflexion pour toutes les tâches ainsi que les risques entourant le forage ascendant.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour le forage de trous ascendants de plus de 20 degrés avec la DR-600 #2923. Elle donne des pistes de réflexion pour toutes les tâches ainsi que les risques entourant le forage ascendant.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "",
  "date_revision": "",
  "source_pdf": "PRO-DD-ST-009-2",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-011",
  "code": "PRO-DD-ST-011",
  "titre": "Récupération du tube carottier lors d'interception de veines d'eau",
  "categorie": "Carottage & tube",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour La récupération du tube carottier lors de l’interception de veines d’eau avec pression significative.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour La récupération du tube carottier lors de l’interception de veines d’eau avec pression significative.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Octobre 2017",
  "date_revision": "Juillet 2021",
  "source_pdf": "PRO-DD-ST-011",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-dd-005",
  "code": "PRO-OP-DD-005",
  "titre": "Démonter et remonter un clam et un chuck (mandrin) sur la foreuse",
  "categorie": "Maintenance",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir les méthodes sécuritaires pour effectuer le démontage et le remontage d’un clam ou d’un chuck (mandrin) sur la foreuse",
  "objectif": "L’objectif de cette procédure est de définir les méthodes sécuritaires pour effectuer le démontage et le remontage d’un clam ou d’un chuck (mandrin) sur la foreuse",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "juin 2018",
  "date_revision": "Mai 2021",
  "source_pdf": "PRO-OP-DD-005",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-dd-012",
  "code": "PRO-OP-DD-012",
  "titre": "Forage à distance avec foreuse au diamant",
  "categorie": "Forage",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour le forage à distance avec une foreuse au diamant.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour le forage à distance avec une foreuse au diamant.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Novembre 2022",
  "date_revision": "",
  "source_pdf": "PRO-OP-DD-012",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-dd-013",
  "code": "PRO-OP-DD-013",
  "titre": "Déplacement d'une foreuse au diamant sur un plancher",
  "categorie": "Déplacement",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour déplacer une foreuse au diamant sur un plancher de forage. Que ce soit avec le FEED EXTENSION, la BARRE DE SWING ou la BARRE DE FORCE.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour déplacer une foreuse au diamant sur un plancher de forage. Que ce soit avec le FEED EXTENSION, la BARRE DE SWING ou la BARRE DE FORCE.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "octobre 2021",
  "date_revision": "Mars 2025",
  "source_pdf": "PRO-OP-DD-013",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "dr600-op-002",
  "code": "DR-600-OP-002",
  "titre": "Déplacement et remorquage de la foreuse DR-600-MU #2923",
  "categorie": "Déplacement",
  "machines": [
   "DR-600"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour déplacer la DR-600-MU par ses propres moyens et la remorquer.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires et efficaces pour déplacer la DR-600-MU par ses propres moyens et la remorquer.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Juillet 2023",
  "date_revision": "Janvier 2026",
  "source_pdf": "DR-600-OP-002",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "ss-dd-st-001",
  "code": "SS-DD-ST-001",
  "titre": "Installation des systèmes de sécurité",
  "categorie": "Sécurité",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires, efficaces et de standardiser l’installation des systèmes de sécurité pour les foreuses aux diamants.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires, efficaces et de standardiser l’installation des systèmes de sécurité pour les foreuses aux diamants.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2019",
  "date_revision": "Août 2023",
  "source_pdf": "SS-DD-ST-001",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "std-dd-installation",
  "code": "STD-DD",
  "titre": "Standard d'installation des sites de forage",
  "categorie": "Installation & plancher",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "Standard d'installation des sites de forage",
  "objectif": "Standard d'installation des sites de forage",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "",
  "date_revision": "",
  "source_pdf": "STD-DD",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-cat-416-001",
  "famille": "commun",
  "code": "PRO-OP-CAT-416-001",
  "titre": "Utilisation du tracteur Caterpillar 416",
  "categorie": "Équipements & véhicules",
  "machines": [
   "Caterpillar 416",
   "Compresseur"
  ],
  "resume": "Méthodes sécuritaires pour l'utilisation du tracteur Caterpillar 416 : tests de freins, déplacements et klaxon dans la rampe, travail dans le panier avant (harnais), transport de matériel et de casings, remorquage de compresseurs et stationnement sous terre.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour l’utilisation du tracteur CATERPILLAR 416",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Décembre 2018",
  "date_revision": "Novembre 2023",
  "source_pdf": "PRO-OP-CAT-416-001",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-bt3-001",
  "code": "PRO-OP-BT3-01",
  "titre": "Utilisation et opération du camion-flèche BT-3 MacLean",
  "categorie": "Équipements & véhicules",
  "machines": [
   "Camion-flèche BT-3 MacLean",
   "Grue Palfinger"
  ],
  "famille": "diamant",
  "resume": "Méthodes sécuritaires pour l'utilisation et l'opération du camion-flèche BT-3 MacLean : formation accréditée, inspection par quart, freins, levage avec la grue Palfinger (capacité 32 000 lb), arrimage des charges, déplacement et stationnement sous terre.",
  "objectif": "L'objectif de cette procédure est de définir des méthodes sécuritaires pour l'utilisation et l'opération du camion-flèche BT-3 MacLean.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "",
  "date_revision": "Janvier 2025",
  "source_pdf": "PRO-OP-BT3-01",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-cim-001",
  "code": "PRO-OP-CIM-001",
  "titre": "Cimentation avec la pompe Chemgrout CG550/030/A",
  "categorie": "Cimentation",
  "machines": [
   "Pompe Chemgrout CG550/030/A"
  ],
  "famille": "diamant",
  "resume": "Méthodes sécuritaires pour l'utilisation de la pompe Chemgrout lors des travaux de cimentation : ÉPI et protection respiratoire (masque power flow), trousse d'urgence, pompage en trous descendants et ascendants, maîtrise de la pression et nettoyage.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour l’utilisation de la pompe CHEMGROUT lors des travaux de cimentation",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Juin 2024",
  "date_revision": "Novembre 2024",
  "source_pdf": "PRO-OP-CIM-001",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 }
]);
