/* PROCÉDURES — FORAGE AU DIAMANT (famille distincte, reliées aux PDF officiels). */
(window.PROCEDURES = window.PROCEDURES || []).push.apply(window.PROCEDURES, [
 {
  "id": "pro-dd-st-001",
  "code": "PRO-DD-ST-001",
  "titre": "Commencement d'un trou de forage avec un core barrel de 1,5 m",
  "categorie": "Forage",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2019",
  "date_revision": "",
  "source_pdf": "a5fe0ad8-PRODDST001_Proc_dure_pour_commencer_dun_trou_de_forage_avec_une_core_barrel_de_15_m.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-002",
  "code": "PRO-DD-ST-002",
  "titre": "Vider le tube carottier",
  "categorie": "Carottage & tube",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2019",
  "date_revision": "",
  "source_pdf": "1a343f78-PRODDST002_Proc_dure_pour_vider_le_tube_carottier_r_v._6_mai_2021.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-003",
  "code": "PRO-DD-ST-003",
  "titre": "Fabrication d'un plancher pour foreuse aux diamants sous terre",
  "categorie": "Installation & plancher",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2019",
  "date_revision": "",
  "source_pdf": "6779632d-PRODDST003_Proc_dure_de_fabrication_dun_plancher_pour_foreuse_aux_diamants_sous_terre_janvier_2025.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-004",
  "code": "PRO-DD-ST-004",
  "titre": "Récupération de tube carottier avec le loading chamber",
  "categorie": "Carottage & tube",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "octobre 2020",
  "date_revision": "",
  "source_pdf": "2c9f8c71-PRODDST004_Proc_dure_de_r_cup_ration_de_tube_avec_le_loading_chamber_Janvier_2026.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-006",
  "code": "PRO-DD-ST-006",
  "titre": "Récupération du tube carottier avec un overshot de surface",
  "categorie": "Carottage & tube",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "",
  "date_revision": "",
  "source_pdf": "187501cb-PRODDST006_R_cup_ration_du_tube_carottier_avec_un_over_shot_de_surface_Janvier_2026.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-007",
  "code": "PRO-DD-ST-007",
  "titre": "Cimentation des trous de forage aux diamants (pompe 435)",
  "categorie": "Cimentation",
  "machines": [
   "Foreuse au diamant",
   "Pompe 435"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2019",
  "date_revision": "Mars 2025",
  "source_pdf": "94008aea-PRODDST007_Proc_dure_de_cimentation_des_trous_de_forage_au_diamant_avec_pompe_435_r_vision_mars_2025.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-008",
  "code": "PRO-DD-ST-008",
  "titre": "Installation du support de tiges de forage",
  "categorie": "Installation & plancher",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2021",
  "date_revision": "Août 2024",
  "source_pdf": "a4bead99-PRODDST008_Proc_dure_dinstallation_du_support___tiges_de_forage_Janvier_2025.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-009-1",
  "code": "PRO-DD-ST-009-1",
  "titre": "Forage de trous ascendants de plus de 20° — STM-1500 / DR-600 #2907",
  "categorie": "Forage",
  "machines": [
   "STM-1500",
   "DR-600"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Juin 2021",
  "date_revision": "Avril 2023",
  "source_pdf": "be29a384-PRODDST0091_Proc_dure_pour_les_trous_ascendants_STM1500_DR600_2907_Avril_2023_.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-009-2",
  "code": "PRO-DD-ST-009-2",
  "titre": "Forage de trous ascendants de plus de 20° — DR-600 #2923",
  "categorie": "Forage",
  "machines": [
   "DR-600"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "",
  "date_revision": "",
  "source_pdf": "6a0c8d03-PRODDST0092_Proc_dure_pour_les_trous_ascendants_DR600_2923_Avril_2023__1.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-dd-st-011",
  "code": "PRO-DD-ST-011",
  "titre": "Récupération du tube carottier lors d'interception de veines d'eau",
  "categorie": "Carottage & tube",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Octobre 2017",
  "date_revision": "Juillet 2021",
  "source_pdf": "3c25fb1e-PRODDST011Proc_dure_de_travail_lors_dinterception_de_veines_deau.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-dd-005",
  "code": "PRO-OP-DD-005",
  "titre": "Démonter et remonter un clam et un chuck (mandrin) sur la foreuse",
  "categorie": "Maintenance",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "juin 2018",
  "date_revision": "Mai 2021",
  "source_pdf": "b97a3cd0-PROOPDD005_Proc_dure_pour_d_monter_et_remonter_un_clam_ou_un_chuck_sur_une_foreuse_mai_2021.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-dd-012",
  "code": "PRO-OP-DD-012",
  "titre": "Forage à distance avec foreuse au diamant",
  "categorie": "Forage",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Novembre 2022",
  "date_revision": "",
  "source_pdf": "83576b64-99d496d0c1d19f21ce6a9d66630ac68466516af968fcf4a37f529459fee1.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-dd-013",
  "code": "PRO-OP-DD-013",
  "titre": "Déplacement d'une foreuse au diamant sur un plancher",
  "categorie": "Déplacement",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "octobre 2021",
  "date_revision": "Mars 2025",
  "source_pdf": "1108769b-PROOPDD013_Proc_dure_de_travail_lors_du_d_placement_dune_foreuse_au_diamant_sur_un_plancher.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "dr600-op-002",
  "code": "DR-600-OP-002",
  "titre": "Déplacement et remorquage de la foreuse DR-600-MU #2923",
  "categorie": "Déplacement",
  "machines": [
   "DR-600"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Juillet 2023",
  "date_revision": "Janvier 2026",
  "source_pdf": "1a1fcf92-DR600OP002_Proc_dure_de_d_placement_et_de_remorquage_de_la_DR600_2923_Janvier_2026.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "ss-dd-st-001",
  "code": "SS-DD-ST-001",
  "titre": "Installation des systèmes de sécurité",
  "categorie": "Sécurité",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "L’objectif de cette",
  "objectif": "L’objectif de cette",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2019",
  "date_revision": "Août 2023",
  "source_pdf": "c8397da1-SSDDST001_Installation_des_syst_mes_de_s_curit_.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "std-dd-installation",
  "code": "STD-DD",
  "titre": "Standard d'installation des sites de forage",
  "categorie": "Installation & plancher",
  "machines": [
   "Foreuse au diamant"
  ],
  "famille": "diamant",
  "resume": "STANDARD D’INSTALLATION SITES DE FORAGE MACHINES ROGER INTERNATIONAL Port",
  "objectif": "STANDARD D’INSTALLATION SITES DE FORAGE MACHINES ROGER INTERNATIONAL Port",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "",
  "date_revision": "",
  "source_pdf": "f95f2751-Standard_dinstallation_sites_de_forage.pdf",
  "langue_source": "fr",
  "notes": "Forage au diamant — fiche reliée au PDF officiel (visionnable et recherchable)."
 }
]);
