/* NOUVELLES PROCEDURES SECTEUR ITH (PRO-ITH-017, bits CUBEX, PIPETUB, STOPEMASTER, VKING). */
(window.PROCEDURES = window.PROCEDURES || []).push.apply(window.PROCEDURES, [
 {
  "id": "pro-ith-017",
  "code": "PRO-ITH-017",
  "titre": "Installation de conduites métalliques dans un trou (foreuse au niveau inférieur)",
  "categorie": "Installation",
  "machines": [
   "ITH",
   "V-30"
  ],
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour effectuer l’installation de tuyaux soudés à l’aide de la foreuse au niveau inférieur.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour effectuer l’installation de tuyaux soudés à l’aide de la foreuse au niveau inférieur.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Mai 2008",
  "date_revision": "Octobre 2022",
  "source_pdf": "PRO-ITH-017",
  "langue_source": "fr",
  "notes": "Secteur ITH — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-001",
  "code": "PRO-OP-001",
  "titre": "Changement des bits de forage sur les CUBEX",
  "categorie": "Maintenance",
  "machines": [
   "ITH"
  ],
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour l’utilisation",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour l’utilisation",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Février 2025",
  "date_revision": "",
  "source_pdf": "PRO-OP-001",
  "langue_source": "fr",
  "notes": "Secteur ITH — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-pt-001",
  "code": "PRO-PT-001",
  "titre": "Utilisation du PIPETUB",
  "categorie": "Manutention",
  "machines": [
   "PIPETUB"
  ],
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour l’utilisation du PIPE-TUB. De sa mobilisation à sa démobilisation ainsi que son opération.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour l’utilisation du PIPE-TUB. De sa mobilisation à sa démobilisation ainsi que son opération.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Mai 2024",
  "date_revision": "",
  "source_pdf": "PRO-PT-001",
  "langue_source": "fr",
  "notes": "Secteur ITH — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-sm-004",
  "code": "PRO-OP-SM-004",
  "titre": "Installation de casing avec le STOPEMASTER",
  "categorie": "Manutention",
  "machines": [
   "STOPEMASTER"
  ],
  "resume": "L’objectif de cette procédure est de définir les méthodes sécuritaires pour l’installation de casing au collet des trous avec le STOPEMASTER.",
  "objectif": "L’objectif de cette procédure est de définir les méthodes sécuritaires pour l’installation de casing au collet des trous avec le STOPEMASTER.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "",
  "date_revision": "",
  "source_pdf": "PRO-OP-SM-004",
  "langue_source": "fr",
  "notes": "Secteur ITH — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-sm-003",
  "code": "PRO-OP-SM-003",
  "titre": "Déplacement et remorquage du STOPEMASTER",
  "categorie": "Déplacement",
  "machines": [
   "STOPEMASTER"
  ],
  "resume": "Déplacement et remorquage du STOPEMASTER",
  "objectif": "",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Avril 2021",
  "date_revision": "Avril 2021",
  "source_pdf": "PRO-OP-SM-003",
  "langue_source": "fr",
  "notes": "Secteur ITH — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-sm-002",
  "code": "PRO-OP-SM-002",
  "titre": "Opération de forage avec le STOPEMASTER",
  "categorie": "Forage",
  "machines": [
   "STOPEMASTER"
  ],
  "resume": "L’objectif de cette procédure est de définir les méthodes sécuritaires pour les opérations de forage avec le STOPEMASTER.",
  "objectif": "L’objectif de cette procédure est de définir les méthodes sécuritaires pour les opérations de forage avec le STOPEMASTER.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Octobre 2008",
  "date_revision": "Avril 2021",
  "source_pdf": "PRO-OP-SM-002",
  "langue_source": "fr",
  "notes": "Secteur ITH — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-sm-001",
  "code": "PRO-OP-SM-001",
  "titre": "Pré-opération du STOPEMASTER",
  "categorie": "Maintenance",
  "machines": [
   "STOPEMASTER"
  ],
  "resume": "L'objectif de cette procédure est de définir des méthodes de travail sécuritaires pour préparer le STOPEMASTER avant son utilisation",
  "objectif": "L'objectif de cette procédure est de définir des méthodes de travail sécuritaires pour préparer le STOPEMASTER avant son utilisation",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Octobre 2008",
  "date_revision": "Avril 2021",
  "source_pdf": "PRO-OP-SM-001",
  "langue_source": "fr",
  "notes": "Secteur ITH — fiche reliée au PDF officiel (visionnable et recherchable)."
 },
 {
  "id": "pro-op-bu-001",
  "code": "PRO-OP-BU-001",
  "titre": "Forage avec la foreuse VKING",
  "categorie": "Forage",
  "machines": [
   "VKING"
  ],
  "resume": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour forer avec la foreuse V-KING.",
  "objectif": "L’objectif de cette procédure est de définir des méthodes sécuritaires pour forer avec la foreuse V-KING.",
  "epi": [],
  "equipements": [],
  "prerequis": [],
  "etapes": [],
  "avertissements": [],
  "consignes_securite": [],
  "valeurs_cles": [],
  "figures": [],
  "historique": [],
  "date_creation": "Septembre 2008",
  "date_revision": "Janvier 2022",
  "source_pdf": "PRO-OP-BU-001",
  "langue_source": "fr",
  "notes": "Secteur ITH — fiche reliée au PDF officiel (visionnable et recherchable)."
 }
]);
