/* ===========================================================================
   QUIZ PAR PROCÉDURE — couvre toute l'information importante de chaque fiche.
   Schéma : window.QUIZ_PROC[id] = [ { q, o:[options], a:index_bonne, e:explication } ]
   Affiché sur la page de détail de chaque procédure (base de connaissances).
   =========================================================================== */
window.QUIZ_PROC = {
  "centralisateur": [
    { "q": "Combien de travailleurs sont obligatoires pour installer le centralisateur ?",
      "o": ["1 seul", "2 travailleurs", "3 travailleurs", "Selon la disponibilité"], "a": 1,
      "e": "L'installation du centralisateur doit TOUJOURS se faire à deux travailleurs." },
    { "q": "Combien pèse chaque pièce du centralisateur ?",
      "o": ["12 livres", "25 livres", "46 livres", "93 livres"], "a": 2,
      "e": "Chaque pièce pèse 46 livres (2 pièces). Bien se positionner avant de soulever." },
    { "q": "Quels outils est-il INTERDIT d'utiliser pour serrer les boulons ?",
      "o": ["Une clé ou un box", "Un wescot ou un pipe wrench", "Une clé Allen", "Un tournevis"], "a": 1,
      "e": "L'utilisation d'un wescot ou d'un pipe wrench n'est pas adéquate. On serre avec une clé ou un box." },
    { "q": "Combien de boulons, locknuts et lockwashers faut-il vérifier ?",
      "o": ["6 de chaque", "8 de chaque", "12 de chaque", "16 de chaque"], "a": 2,
      "e": "Vérifier la présence des 12 boulons, 12 locknuts et 12 lockwashers avant le serrage." },
    { "q": "À quel intervalle installe-t-on un centralisateur ?",
      "o": ["Tous les 20 pieds", "Tous les 40 pieds", "Tous les 60 pieds", "Tous les 100 pieds"], "a": 1,
      "e": "Un centralisateur s'installe tous les 40 pieds (ou selon les conditions)." },
    { "q": "Y a-t-il une séquence imposée pour serrer les boulons et écrous ?",
      "o": ["Oui, en étoile", "Oui, dans le sens horaire", "Non, aucune séquence imposée", "Oui, de bas en haut"], "a": 2,
      "e": "Il n'y a pas de séquence d'installation ou de serrage des boulons et des écrous." },
    { "q": "Sur quoi faut-il maintenir une tension pendant le serrage ?",
      "o": ["Sur les boyaux", "Sur les lockwashers", "Sur le mât", "Sur le câble"], "a": 1,
      "e": "Serrer tous les boulons en maintenant une tension sur les lockwashers avec l'outil adéquat." },
    { "q": "Quel risque faut-il éviter en insérant les boulons dans les trous ?",
      "o": ["Endommager les filets", "Échapper la pièce", "Brûlure", "Choc électrique"], "a": 0,
      "e": "Attention à ne pas endommager les filets des boulons quand vous les entrez dans les trous." },
    { "q": "Comment sont répartis les boulons sur le centralisateur ?",
      "o": ["Tous du même côté", "6 dans un sens et 6 dans l'autre", "4 et 8", "Au hasard"], "a": 1,
      "e": "La répartition est de 6 boulons dans un sens et 6 dans l'autre sens." },
    { "q": "Quel équipement de protection est requis pour manipuler les pièces ?",
      "o": ["Aucun", "Des gants", "Un harnais", "Un masque"], "a": 1,
      "e": "Le port de gants est requis pour manipuler les pièces lourdes du centralisateur." }
  ],
  "pro-mec-011": [
    { "q": "Que faut-il faire AVANT tout travail de changement de coupling ?",
      "o": ["Démarrer la foreuse", "Cadenasser la foreuse", "Vidanger l'huile", "Appeler un électricien"], "a": 1,
      "e": "Cadenasser la foreuse avant d'entreprendre tout travail de changement de coupling." },
    { "q": "Une fois la sangle desserrée, par quoi la pompe est-elle retenue ?",
      "o": ["Par le bell housing", "Par les boyaux hydrauliques", "Par le shaft", "Par rien"], "a": 1,
      "e": "La pompe n'est plus retenue que par les boyaux : il faut la retenir avec les mains sur les boyaux." },
    { "q": "Où faut-il ÉVITER de mettre les mains lors du retrait de la pompe ?",
      "o": ["Sur les boyaux", "Sous la pompe", "Sur la sangle", "Sur le cadre"], "a": 1,
      "e": "Éviter de se mettre les mains sous la pompe et protéger ses doigts des coincements." },
    { "q": "En quel matériau est fait le bell housing ?",
      "o": ["Acier", "Fonte", "Aluminium", "Plastique"], "a": 2,
      "e": "Le bell housing est en aluminium : un matériau qui s'endommage facilement." },
    { "q": "Avec quel outil peut-on frapper le bell housing pour le décoller ?",
      "o": ["Une masse de caoutchouc", "Une masse d'acier", "Un pipe wrench", "Une barre à clous"], "a": 0,
      "e": "Le bell housing étant en aluminium, utiliser uniquement une masse de caoutchouc pour ne pas l'endommager." },
    { "q": "Si la coupling est collée, quel composant faut-il éviter d'endommager en frappant la pry bar ?",
      "o": ["Le bell housing", "Le shaft du moteur électrique", "La sangle", "Le couvercle"], "a": 1,
      "e": "Frapper sur la pry bar en prenant garde de ne pas endommager le shaft du moteur électrique." },
    { "q": "Quel produit applique-t-on sur les shafts avant le remontage ?",
      "o": ["De la graisse ordinaire", "De l'antiseize", "De l'huile", "Du WD-40"], "a": 1,
      "e": "Bien nettoyer les shafts et l'épaulement, puis appliquer de l'antiseize avant le remontage." },
    { "q": "Comment doit être la coupling par rapport au shaft avant de serrer la barrure ?",
      "o": ["En retrait", "Dépassant de 1 cm", "FLUSH (à égalité)", "Peu importe"], "a": 2,
      "e": "S'assurer que la coupling est « FLUSH » au shaft avant de serrer au maximum la barrure." },
    { "q": "Comment insère-t-on d'abord les 2 boulons de la pompe ?",
      "o": ["À la clé à choc", "À la main", "Au pistolet", "En forçant"], "a": 1,
      "e": "Insérer à la main les 2 boulons pour vérifier le bon alignement avant de serrer à la clé." },
    { "q": "Pourquoi faut-il remettre le couvercle de plastique à la fin ?",
      "o": ["Pour l'esthétique", "Pour rétablir la protection (début d'incendie déjà survenu)", "Pour le poids", "Ce n'est pas requis"], "a": 1,
      "e": "Le couvercle rétablit la protection : mesure issue d'un début d'incendie causé par surchauffe." },
    { "q": "Quel danger est associé au bell housing et au couvercle ?",
      "o": ["Choc électrique", "Risque de feu si surchauffe", "Explosion", "Gel"], "a": 1,
      "e": "Un début d'incendie a déjà été causé par la surchauffe du bell housing et du couvercle." },
    { "q": "Quelle clé Allen sert à la barrure de la coupling de la pompe ?",
      "o": ["3/16", "1/4", "5/16", "1/2"], "a": 2,
      "e": "La barrure de la coupling de la pompe se fait avec une clé Allen 5/16." }
  ],
  "pro-op-ith-002": [
    { "q": "Que faut-il faire avant d'intervenir pour dévisser des tiges ?",
      "o": ["Mettre la foreuse en marche", "Appliquer le cadenassage", "Retirer les clés", "Rien de spécial"], "a": 1,
      "e": "Appliquer la procédure de cadenassage avant d'intervenir." },
    { "q": "Combien de tire-fort doit-on utiliser ?",
      "o": ["Un seul", "Deux", "Trois", "Autant que nécessaire"], "a": 0,
      "e": "On n'utilise qu'un seul tire-fort, dont les crochets sont munis de linguet." },
    { "q": "Quelle caractéristique les crochets du tire-fort doivent-ils avoir ?",
      "o": ["Être peints en rouge", "Être munis de linguet", "Être neufs", "Être doublés"], "a": 1,
      "e": "Les crochets doivent obligatoirement être munis de linguet." },
    { "q": "Quelle est la charge certifiée de l'ancrage du mât à ne jamais dépasser ?",
      "o": ["1000 kg", "1500 kg", "2500 kg", "5000 kg"], "a": 2,
      "e": "L'ancrage du mât est certifié pour 2500 kg : ne jamais dépasser cette charge en tension." },
    { "q": "Avant de donner un coup de masse sur le manche de la clé, que faut-il vérifier ?",
      "o": ["Que les pieds sont sur une surface solide", "Que la foreuse tourne", "Que le mât est levé", "Que la radio fonctionne"], "a": 0,
      "e": "S'assurer d'avoir les pieds sur une surface solide avant de frapper avec la masse." },
    { "q": "Lors d'un coup de masse, où personne ne doit-il se trouver ?",
      "o": ["Derrière le travailleur", "Dans la ligne de la masse si elle est échappée", "Près du mât", "Sur la console"], "a": 1,
      "e": "Personne ne doit se trouver dans la ligne de la masse advenant qu'elle soit échappée." },
    { "q": "Dans quelle position met-on le mât pour éviter que la clé à saver sub tombe ?",
      "o": ["Verticale", "À l'horizontale", "À 45 degrés", "Peu importe"], "a": 1,
      "e": "Positionner le mât à l'horizontale avant d'installer la clé pour éviter qu'elle tombe." },
    { "q": "Où place-t-on le gearbox pour avoir l'espace nécessaire ?",
      "o": ["Le plus près des tables", "Le plus loin possible des tables", "Sur la console", "Sous le mât"], "a": 1,
      "e": "Placer le gearbox le plus loin possible des tables pour disposer de l'espace nécessaire." },
    { "q": "Combien de manilles sont requises et de quelle dimension ?",
      "o": ["1 manille 1/2", "2 manilles 3/4", "4 manilles 3/4", "2 manilles 1''"], "a": 1,
      "e": "Deux manilles de 3/4 sont requises." },
    { "q": "Quand peut-on retirer les clés et décadenasser ?",
      "o": ["Dès le début", "À la moitié du travail", "Une fois l'opération terminée", "Jamais"], "a": 2,
      "e": "Retirer les clés et décadenasser uniquement une fois l'opération terminée." },
    { "q": "Quels EPI sont mentionnés pour cette tâche ?",
      "o": ["Seulement des gants", "Casque, lunettes, gants et bottes", "Seulement un harnais", "Aucun"], "a": 1,
      "e": "Casque et lunettes, gants et bottes sont les EPI de base pour cette opération." }
  ],
  "pro-op-ith-002a": [
    { "q": "Quel outil de mise en tension est utilisé dans cette procédure ?",
      "o": ["Un tire-fort", "Un palan à levier (come along)", "Un treuil électrique", "Un vérin"], "a": 1,
      "e": "Cette procédure utilise un palan à levier (come along) pour dévisser les tiges." },
    { "q": "Combien de palans à levier (come along) utilise-t-on ?",
      "o": ["Un seul", "Deux", "Trois", "Selon le besoin"], "a": 0,
      "e": "On utilise un seul come along." },
    { "q": "Pour quelle charge l'ancrage doit-il être certifié ?",
      "o": ["1500 kg", "2000 kg", "2500 kg", "3000 kg"], "a": 2,
      "e": "Utiliser uniquement un ancrage certifié pour une charge de 2500 kg, sans la dépasser." },
    { "q": "Les crochets du come along doivent être munis de quoi ?",
      "o": ["De linguets de sécurité", "De peinture", "D'un cadenas", "D'un ressort"], "a": 0,
      "e": "S'assurer que les crochets du palan à levier sont munis de linguets de sécurité." },
    { "q": "Dans quelle position met-on la flèche (boom) ?",
      "o": ["Verticale", "Horizontale", "Inclinée à 60°", "Peu importe"], "a": 1,
      "e": "Mettre la flèche (boom) à l'horizontale pour éviter que la clé à saver sub tombe." },
    { "q": "Combien de manilles et de quelle dimension ?",
      "o": ["1 manille 3/4", "2 manilles 3/4", "2 manilles 1''", "4 manilles 1/2"], "a": 1,
      "e": "On utilise 2 manilles de 3/4." },
    { "q": "Avant de reprendre le travail, que faut-il faire des deux clés ?",
      "o": ["Les laisser en place", "Les retirer et décadenasser", "Les huiler", "Les ranger dans le mât"], "a": 1,
      "e": "Retirer les deux clés et décadenasser l'équipement avant de reprendre le travail." },
    { "q": "Lors d'un coup de masse, quelle est la double précaution ?",
      "o": ["Gants et lunettes", "Pieds sur surface solide ET personne dans l'axe de chute", "Casque et bottes", "Radio et lampe"], "a": 1,
      "e": "Pieds sur une surface solide et personne dans l'axe (ligne de chute) si la masse tombe." },
    { "q": "Où place-t-on le gearbox pour installer la clé ?",
      "o": ["Près des tables", "Loin des tables", "Au sol", "Sur la console"], "a": 1,
      "e": "Éloigner le gearbox le plus possible des tables pour avoir l'espace d'installer la clé." }
  ],
  "pro-op-ith-003": [
    { "q": "Que faut-il faire des accessoires de levage avant le déplacement ?",
      "o": ["Les huiler", "Les inspecter et remplacer tout accessoire avec anomalie", "Les peindre", "Rien"], "a": 1,
      "e": "Inspecter tous les accessoires de levage; tout accessoire avec anomalie doit obligatoirement être remplacé." },
    { "q": "Peut-on modifier les composantes de l'équipement ?",
      "o": ["Oui, au besoin", "Non, aucune modification n'est autorisée", "Oui, avec accord verbal", "Seulement les soudures"], "a": 1,
      "e": "L'utilisation de composantes approuvées est obligatoire : aucune modification n'est autorisée." },
    { "q": "Que faut-il faire avant de manipuler le câble électrique ?",
      "o": ["Le couper", "Fermer le disjoncteur et cadenasser", "Le mouiller", "Rien"], "a": 1,
      "e": "Fermer le disjoncteur du panneau et ne remettre l'alimentation à ON que juste avant de déplacer." },
    { "q": "Que faut-il purger avant de découpler les boyaux ?",
      "o": ["Les boyaux à air et à eau", "L'huile moteur", "Le réservoir de carburant", "Rien"], "a": 0,
      "e": "Il est très important de purger les boyaux à air (filtre, receiver) et le boyau à eau avant de les découpler." },
    { "q": "Combien d'élingues et de quelle taille pour relier le traîneau/remorque ?",
      "o": ["1 élingue 1/2''", "2 élingues d'au moins 1'' x 8 pieds", "2 élingues de 4 pieds", "3 élingues 1''"], "a": 1,
      "e": "Relier avec deux élingues d'au moins 1'' x 8 pieds, fixées avec des manilles." },
    { "q": "Quelle dimension minimale pour les manilles de fixation des élingues ?",
      "o": ["1/2''", "3/4''", "1'' 1/4", "2''"], "a": 2,
      "e": "Les manilles doivent être de 1'' 1/4 minimum." },
    { "q": "Où l'opérateur doit-il se placer lors de l'embarquement de la foreuse ?",
      "o": ["À côté de la foreuse", "À l'intérieur du panier avec la chaîne garde-corps", "Sur le mât", "Dans la rampe"], "a": 1,
      "e": "L'opérateur doit toujours se placer à l'intérieur du panier et mettre la chaîne garde-corps." },
    { "q": "Comment arrime-t-on la foreuse pour le transport ?",
      "o": ["D'un seul côté", "De chaque côté pour l'empêcher d'avancer ou reculer", "Par le mât", "On ne l'arrime pas"], "a": 1,
      "e": "Arrimer la foreuse de chaque côté pour l'empêcher d'avancer ou de reculer." },
    { "q": "Que doit-on vérifier sur la foreuse avant le transport ?",
      "o": ["Qu'aucune pièce libre ni outil ne s'y trouve", "Que le moteur tourne", "Que les pneus sont gonflés", "Que la radio fonctionne"], "a": 0,
      "e": "S'assurer qu'aucune pièce libre ni outil ne se trouve sur la foreuse avant le transport." },
    { "q": "Après le déplacement, peut-on attacher le traîneau au mur ?",
      "o": ["Oui, c'est recommandé", "Non, jamais; le laisser par terre et le signaler", "Seulement avec une chaîne", "Seulement la nuit"], "a": 1,
      "e": "Ne jamais attacher le traîneau au mur; le laisser par terre et le signaler avec un ruban jaune." },
    { "q": "Combien de boulons doivent être en place sur la barre de tir du compresseur ?",
      "o": ["1 boulon", "2 boulons", "4 boulons", "Aucun"], "a": 1,
      "e": "Verrouiller la barre de tir avec le boulon; s'assurer que les deux boulons sont en place pour limiter le pivot." },
    { "q": "Peut-on déplacer la foreuse SANS remorque dans la rampe ?",
      "o": ["Oui, à basse vitesse", "Non, c'est interdit dans la rampe", "Oui, sur courte distance", "Oui, avec escorte"], "a": 1,
      "e": "Le déplacement sans remorque est permis seulement à plat, sur courtes distances et à basse vitesse; INTERDIT dans la rampe." },
    { "q": "Sans remorque, avec quelles manilles installe-t-on la barre de tir ?",
      "o": ["Manilles 1/2''", "Manilles 3/4'' (raccord chargeuse 1 1/4'')", "Manilles 2''", "Sans manille"], "a": 1,
      "e": "Sans remorque : barre de tir avec manilles 3/4'', raccord à la chargeuse-navette avec manille 1 1/4'', plus chaîne de sécurité." },
    { "q": "Que faut-il maintenir avec l'opérateur de la chargeuse durant le déplacement sans remorque ?",
      "o": ["Le silence radio", "Une bonne communication", "Une distance de 50 m", "Rien de particulier"], "a": 1,
      "e": "Maintenir une bonne communication avec l'opérateur de la chargeuse durant le déplacement." }
  ],
  "pro-op-ith-004": [
    { "q": "Dans quelle position doivent être les leviers avant de mettre l'unité sous tension ?",
      "o": ["En marche avant", "Au neutre (point mort)", "En rotation", "Peu importe"], "a": 1,
      "e": "Vérifier tous les leviers et les mettre au neutre (point mort) avant de mettre sous tension." },
    { "q": "Avec quoi manipule-t-on l'extension du câble électrique sous tension ?",
      "o": ["À mains nues", "Avec le crochet de plastique", "Avec une pince métallique", "Avec des gants en cuir"], "a": 1,
      "e": "Ne manipuler l'extension du câble sous tension qu'avec le crochet de plastique." },
    { "q": "Au point de forage, comment met-on la foreuse hors tension ?",
      "o": ["En débranchant le câble", "Avec le E-STOP", "En coupant le moteur diesel", "On ne la coupe pas"], "a": 1,
      "e": "Au point de forage, mettre la foreuse hors tension avec le E-STOP." },
    { "q": "À quelle hauteur accroche-t-on le câble électrique au mur ?",
      "o": ["Au sol", "À 4 à 5 pieds du banc (niveau de la poitrine)", "Au plafond", "À 10 pieds"], "a": 1,
      "e": "Accrocher le câble au mur au niveau de la poitrine (4 à 5 pieds du banc) pour éviter tout contact." },
    { "q": "Où installe-t-on un dispositif de retenue (whip check) ?",
      "o": ["Seulement au début du boyau", "À chaque joint", "À la fin seulement", "Nulle part"], "a": 1,
      "e": "Installer les dispositifs de retenue (whip check) à chaque joint des boyaux." },
    { "q": "Quelle est la température des boyaux tressés des compresseurs ?",
      "o": ["100 °F", "300 °F", "800 °F", "1200 °F"], "a": 2,
      "e": "Les boyaux tressés haute température des compresseurs (CUBEX, surcompresseurs) atteignent 800 °F." },
    { "q": "Que fait-on aux boyaux à air juste avant de les connecter ?",
      "o": ["On les mouille", "On les souffle", "On les huile", "On les chauffe"], "a": 1,
      "e": "Souffler les boyaux à air avant la connexion et installer les whip check à chaque joint." },
    { "q": "Quelle distance minimale entre la barricade et les premières pièces de matériel ?",
      "o": ["1 mètre", "3 mètres (10 pieds)", "7 mètres", "15 mètres"], "a": 1,
      "e": "Laisser au moins 3 mètres (10 pieds) entre la barricade et les premières pièces de matériel." },
    { "q": "Quelle distance minimale obligatoire entre le mât et la console ?",
      "o": ["0,5 mètre", "1 mètre", "1,5 mètre", "3 mètres"], "a": 2,
      "e": "Respecter obligatoirement une distance minimale de 1,5 mètre entre le mât et la console." },
    { "q": "Quand une pièce est en mouvement, où ne doit-on jamais se placer ?",
      "o": ["Derrière la console", "Entre la console et le mât, ni à moins de 1,5 m du mât", "Dans le panier", "Près de la barricade"], "a": 1,
      "e": "Aucun travailleur ne doit se placer entre la console et le mât, ni à moins de 1,5 m du mât de tous les côtés." },
    { "q": "Lors du défoncement de trous, comment pousse-t-on ?",
      "o": ["Avec rotation rapide", "SANS rotation, 1 tige de plus que la longueur du défoncement", "En reculant", "Avec 2 tiges de plus"], "a": 1,
      "e": "Lors du défoncement, pousser SANS ROTATION 1 tige de plus que la longueur du défoncement." },
    { "q": "Avant de manipuler les tiges, dans quel état doit être la foreuse ?",
      "o": ["En rotation", "Boîte de vitesse relevée/arrêtée et foreuse au point mort", "En marche avant", "Sous tension maximale"], "a": 1,
      "e": "Relever et arrêter la boîte de vitesse et mettre la foreuse au point mort avant de manipuler les tiges." },
    { "q": "Quel danger faut-il rechercher avant de déplacer l'unité à la première ligne de forage ?",
      "o": ["Des fuites d'huile", "Des explosifs restants ou non détonnés", "De la glace", "Des animaux"], "a": 1,
      "e": "Laver la zone, vérifier l'écaillage et inspecter à la recherche d'explosifs restants ou non détonnés." },
    { "q": "À partir de quelle profondeur privilégie-t-on un 2e travailleur ?",
      "o": ["50 pieds", "100 pieds", "200 pieds et plus", "500 pieds"], "a": 2,
      "e": "On privilégie un 2e travailleur pour le forage et l'arrachement des tiges des trous de 200 pieds et plus." },
    { "q": "Quelle distance doit-on respecter entre la foreuse et le surcompresseur ?",
      "o": ["3 mètres", "5 mètres", "7 mètres", "10 mètres"], "a": 2,
      "e": "Respecter une distance de 7 mètres entre la foreuse et le surcompresseur." },
    { "q": "Quel diamètre de trou exige le chariot de transport (ou cloche et chaîne) ?",
      "o": ["Moins de 3 po", "Plus de 6 ½ po", "Exactement 4 po", "Tous les diamètres"], "a": 1,
      "e": "Pour les trous de plus de 6 ½ po de diamètre, utiliser le chariot de transport ou la cloche et la chaîne." }
  ],
  "pro-op-ith-005": [
    { "q": "L'installation du couvert sur la monterie est-elle obligatoire ?",
      "o": ["Seulement la nuit", "Oui, en tout temps lors du forage V-30 en descendant", "Seulement si demandé", "Non"], "a": 1,
      "e": "L'installation du couvert (M.R.I. ou client) sur la monterie est obligatoire en tout temps lors du forage V-30 en descendant." },
    { "q": "Un employé peut-il descendre dans la monterie de 30 pouces pour récupérer une pièce ?",
      "o": ["Oui, avec un harnais", "Oui, si le superviseur l'autorise", "Non, c'est strictement interdit à quiconque en tout temps", "Oui, pour les tiges seulement"], "a": 2,
      "e": "Il est STRICTEMENT INTERDIT d'entrer dans la monterie de 30 pouces; M.R.I. a des équipements adaptés pour extraire les matériaux brisés." },
    { "q": "Que faut-il éviter par rapport à la tête V-30 si elle se décroche ?",
      "o": ["La toucher", "Se tenir dans son axe de déplacement possible", "La regarder", "La nettoyer"], "a": 1,
      "e": "Ne jamais se tenir dans l'axe de déplacement possible de la tête si elle se décroche; contrôles au neutre." },
    { "q": "Pendant le forage, qui peut circuler en avant de la foreuse ?",
      "o": ["L'aide-foreur", "Personne", "Le superviseur", "L'électricien"], "a": 1,
      "e": "Aucune circulation n'est permise en avant de la foreuse pendant le forage du trou." },
    { "q": "Quand le couvert est enlevé, comment doivent être les employés près de la monterie ?",
      "o": ["À 5 m", "Attachés (longe restrictive ou harnais + bloc rétractable)", "Assis", "Avec un casque seulement"], "a": 1,
      "e": "Ils doivent être attachés au moyen d'une longe restrictive empêchant l'accès au trou, ou d'un harnais avec bloc rétractable approuvé." },
    { "q": "Peut-on interchanger les boyaux basse et haute pression ?",
      "o": ["Oui", "Non, jamais (les stem nuts l'empêchent)", "Oui, si même diamètre", "Seulement à froid"], "a": 1,
      "e": "Ne jamais interchanger les boyaux basse et haute pression; les stem nuts sont conçus pour l'empêcher." },
    { "q": "À quelle distance du mât positionne-t-on la console ?",
      "o": ["0,5 m", "1 m", "1,5 m", "3 m"], "a": 2,
      "e": "Positionner la console à 1,5 mètre du mât pour protéger les travailleurs des projections de roches." },
    { "q": "Quelle distance entre la foreuse et le surcompresseur ?",
      "o": ["3 m", "5 m", "7 m", "10 m"], "a": 2,
      "e": "Maintenir une distance de 7 mètres entre la foreuse et le surcompresseur." },
    { "q": "À partir de quelle longueur de monterie installe-t-on un centralisateur ?",
      "o": ["Plus de 20 pieds", "Plus de 40 pieds", "Plus de 100 pieds", "Jamais"], "a": 1,
      "e": "Installer un centralisateur pour stabiliser les tiges lorsque la monterie dépasse 40 pieds." },
    { "q": "En cas de bris de tige, que coupe-t-on immédiatement ?",
      "o": ["Seulement l'eau", "L'alimentation électrique ET l'air comprimé", "Seulement l'électricité", "Rien"], "a": 1,
      "e": "Arrêter immédiatement le forage et fermer l'interrupteur électrique et l'alimentation en air comprimé." },
    { "q": "Après un bris de tige, comment protège-t-on l'accès au chantier ?",
      "o": ["Avec un simple cône", "Barricade, ruban rouge et/ou panneaux ACCÈS INTERDIT", "On laisse ouvert", "Avec une corde jaune"], "a": 1,
      "e": "Installer une barricade, un ruban rouge et/ou des panneaux ACCÈS INTERDIT et aviser le contremaître." },
    { "q": "Pour récupérer une tige brisée, comment opère-t-on la foreuse ?",
      "o": ["De près, manuellement", "Avec les contrôles à distance, dans un endroit sécuritaire éloigné", "En entrant dans la monterie", "On ne récupère pas"], "a": 1,
      "e": "Utiliser les contrôles à distance placés dans un endroit sécuritaire éloigné de la foreuse." },
    { "q": "Quel EPI antichute porte-t-on si le couvert est enlevé et qu'on s'expose à une chute ?",
      "o": ["Des gants", "Un harnais de sécurité antichute attaché à un ancrage approuvé", "Un masque", "Des bottes"], "a": 1,
      "e": "Porter le harnais de sécurité antichute attaché à des points d'ancrage approuvés par le client." },
    { "q": "Quelle est la température des boyaux des compresseurs (CUBEX/surcompresseur) ?",
      "o": ["200 °F", "500 °F", "800 °F", "1500 °F"], "a": 2,
      "e": "Les boyaux tressés haute température des compresseurs atteignent 800 °F." },
    { "q": "Quel est le diamètre final de la monterie ?",
      "o": ["10 pouces", "20 pouces", "30 pouces", "6 ½ pouces"], "a": 2,
      "e": "Le diamètre du trou final (monterie) est de 30 pouces (trou pilote 6½ po, alésage du guide 10 po)." }
  ],
  "pro-op-ith-006": [
    { "q": "Avant de mettre l'unité sous tension, les leviers sont mis...",
      "o": ["En rotation", "Au neutre (point mort)", "En marche avant", "Au maximum"], "a": 1,
      "e": "Vérifier que tous les leviers de commande sont au neutre (point mort) avant la mise sous tension." },
    { "q": "Avec quoi manipule-t-on l'extension du câble sous tension ?",
      "o": ["Le crochet de plastique", "Une pince", "Les mains", "Une corde"], "a": 0,
      "e": "Si l'extension doit être manipulée sous tension, utiliser le crochet de plastique." },
    { "q": "Au point de forage, comment coupe-t-on la foreuse ?",
      "o": ["Au E-STOP", "En débranchant", "Au disjoncteur principal de la mine", "On ne coupe pas"], "a": 0,
      "e": "Mettre la foreuse hors tension en appuyant sur le E-STOP au point de forage." },
    { "q": "À quelle hauteur accroche-t-on le câble électrique au mur ?",
      "o": ["Au sol", "4 à 5 pieds du banc (niveau poitrine)", "Au plafond", "10 pieds"], "a": 1,
      "e": "Accrocher le câble au mur à 4-5 pieds du banc (niveau de la poitrine) pour éviter tout contact." },
    { "q": "Où installe-t-on un whip check sur les boyaux d'air ?",
      "o": ["À chaque joint", "Seulement au compresseur", "À la fin du boyau", "Nulle part"], "a": 0,
      "e": "Installer les dispositifs de retenue (whip check) à chaque joint des boyaux d'air." },
    { "q": "Pourquoi ne peut-on pas interchanger les boyaux basse et haute pression ?",
      "o": ["Ils sont identiques", "Les stem nuts des boyaux 2½ po sont faits pour l'empêcher", "Ils sont peints différemment", "C'est permis"], "a": 1,
      "e": "Les stem nuts des boyaux de 2½ po. empêchent l'interchange entre basse et haute pression pour éviter les accidents." },
    { "q": "Où suspend-on les boyaux par rapport au câble électrique ?",
      "o": ["Au-dessus du câble", "En-dessous du câble électrique", "Enroulés autour", "Au sol seulement"], "a": 1,
      "e": "Suspendre tous les boyaux en-dessous du câble électrique pour éliminer tout contact avec roches branlantes ou équipement." },
    { "q": "Quelle distance minimale entre la barricade et les premières pièces de matériel ?",
      "o": ["1 m", "3 mètres (10 pieds)", "7 m", "15 m"], "a": 1,
      "e": "Laisser au moins 3 mètres (10 pieds) entre la barricade et les premières pièces de matériel." },
    { "q": "Quand doit-on porter tout l'EPI requis ?",
      "o": ["Jamais", "Lors de l'affûtage et du façonnement des forets", "Seulement au transport", "Seulement au cadenassage"], "a": 1,
      "e": "Porter tout l'EPI requis lors de l'affûtage et du façonnement des forets (affûteurs et meules)." },
    { "q": "Pendant le forage, peut-on circuler en avant de la foreuse ?",
      "o": ["Oui", "Non, c'est interdit à toute personne", "Oui, à 1 m", "Seulement l'aide-foreur"], "a": 1,
      "e": "Interdire à toute personne de circuler en avant de la foreuse pendant le forage." },
    { "q": "Avant de manipuler les tiges, dans quel état est la foreuse ?",
      "o": ["En rotation", "Boîte de vitesse relevée/arrêtée et foreuse au point mort", "Sous tension", "En transport"], "a": 1,
      "e": "Relever et arrêter la boîte de vitesse et placer la foreuse au point mort avant toute manipulation des tiges." },
    { "q": "Quel grade de chaîne utilise-t-on pour suspendre et positionner la tête V-30 ?",
      "o": ["Grade 30", "Grade 70", "Grade 80 (7100 lbs)", "Aucun grade précis"], "a": 2,
      "e": "Utiliser une chaîne de grade 80 (7100 lbs) pour suspendre et positionner la tête V-30." },
    { "q": "Quel moyen de communication est requis entre les niveaux lors du raccordement de la tête ?",
      "o": ["Aucun", "Radio ou système femco fonctionnel", "Signaux de la main", "Un sifflet"], "a": 1,
      "e": "Disposer d'un moyen de communication (radio ou femco) fonctionnel aux niveaux supérieur et inférieur." },
    { "q": "En cas de bris de tige, qui doit-on aviser avant de reprendre le forage ?",
      "o": ["L'aide-foreur", "Le contremaître (présence requise jusqu'à la fin)", "Personne", "Le fournisseur"], "a": 1,
      "e": "Aviser le contremaître : aucun forage avant son arrivée, sa présence est requise jusqu'à la fin de la récupération." }
  ],
  "pro-op-ith-007": [
    { "q": "Quelle est la zone d'exclusion autour du mât pendant le forage ?",
      "o": ["1,5 m", "3 m", "5 mètres", "10 m"], "a": 2,
      "e": "Interdire à toute personne de circuler à moins de 5 mètres du mât pendant le forage." },
    { "q": "À quelle distance du point de forage place-t-on la commande de forage ?",
      "o": ["1 m", "3 m", "5 mètres", "15 m"], "a": 2,
      "e": "Positionner la commande à 5 mètres du point de forage pour être à l'abri des projections de roche." },
    { "q": "Lors de l'entretien ou d'un bris de tige, où doit être le travailleur (ou la manette) ?",
      "o": ["Tout près de la tête", "À 5 m de la ligne de forage et hors de la ligne de tir des chutes", "Sous la monterie", "Dans le mât"], "a": 1,
      "e": "Le travailleur ou la manette doit être à 5 mètres de la ligne de forage et hors de la ligne de tir de chutes de la monterie." },
    { "q": "Quelle distance entre la foreuse et le compresseur (surcompresseur) ?",
      "o": ["3 m", "5 m", "7 mètres", "12 m"], "a": 2,
      "e": "Maintenir une distance de 7 mètres entre la foreuse et le compresseur." },
    { "q": "Avec quoi manipule-t-on l'extension de câble sous tension ?",
      "o": ["Le crochet de plastique", "Une clé", "Les mains gantées", "Une pince"], "a": 0,
      "e": "Manipuler toute extension de câble sous tension uniquement avec le crochet de plastique." },
    { "q": "À quoi sert la cage de protection à grillage à mailles soudées ?",
      "o": ["À décorer", "À canaliser les débris loin de l'opérateur", "À ranger les outils", "À supporter le mât"], "a": 1,
      "e": "La cage de protection canalise les débris loin de l'opérateur. Nettoyer déflecteurs et grillages avant de s'exposer dessous." },
    { "q": "Lors du soufflage des déblais, quelle précaution prend-on ?",
      "o": ["Porter un masque et ne pas s'exposer sous le trou de la V-30", "Se placer sous le trou", "Retirer le masque", "Couper l'air"], "a": 0,
      "e": "Porter un masque lors du soufflage des déblais et ne pas s'exposer directement sous le trou de la V-30." },
    { "q": "Peut-on se tenir dans l'axe de déplacement de la tête V-30 ?",
      "o": ["Oui, brièvement", "Non, jamais si elle se décroche", "Oui, avec un harnais", "Seulement à l'arrêt"], "a": 1,
      "e": "Ne jamais se tenir dans l'axe de déplacement possible de la tête si elle se décroche; contrôles au neutre." },
    { "q": "À quel intervalle installe-t-on des centralisateurs quand la monterie dépasse 40 pieds ?",
      "o": ["Aux 20 pieds", "Aux 40 pieds", "Aux 100 pieds", "Un seul suffit"], "a": 1,
      "e": "Installer des centralisateurs aux 40 pieds lorsque la monterie dépasse 40 pieds pour stabiliser les tiges." },
    { "q": "Dans quel état doivent rester les accès entre les contrôles, le mât et le support à tige ?",
      "o": ["Peu importe", "Libres en tout temps (pas de boyaux, casing ni roche)", "Couverts de bâches", "Barricadés"], "a": 1,
      "e": "Garder libres en tout temps les accès séparant les contrôles, le mât et le support à tige." },
    { "q": "Quelle hauteur plancher-toit faut-il maintenir ?",
      "o": ["6 à 8 pieds", "12 à 14 pieds (max 4,3 m)", "20 pieds", "Aucune exigence"], "a": 1,
      "e": "Maintenir une hauteur plancher-toit de 12 à 14 pieds; au-delà de 4,3 m (14 pi), relever le plancher avec de la roche abattue." },
    { "q": "Comment transporte-t-on le marteau ?",
      "o": ["À bout de bras", "Avec le chariot de transport stable (aide pour trous 200 pi et +)", "En le faisant rouler", "Sur l'épaule"], "a": 1,
      "e": "Transporter le marteau avec le chariot stable; demander de l'aide d'un aide-foreur pour les trous de 200 pieds et plus." },
    { "q": "Que faut-il faire avant d'opérer la foreuse à distance pour récupérer une tige brisée ?",
      "o": ["Rien", "Une analyse de risque", "Appeler le fournisseur", "Démonter le mât"], "a": 1,
      "e": "Une analyse de risque doit être effectuée avant d'opérer la foreuse à distance pour récupérer une tige brisée." },
    { "q": "Que coupe-t-on immédiatement lors d'un bris de tige ?",
      "o": ["L'eau seulement", "L'interrupteur électrique ET l'alimentation en air comprimé", "Le moteur diesel", "Rien"], "a": 1,
      "e": "Lors d'un bris de tige, fermer immédiatement l'interrupteur électrique et l'alimentation en air comprimé." }
  ],
  "pro-op-ith-008": [
    { "q": "Si un taillant se brise, peut-on descendre au fond de la monterie pour le récupérer ?",
      "o": ["Oui, avec un harnais", "Oui, si le superviseur l'autorise", "Non, c'est strictement défendu à quiconque en tout temps", "Oui, rapidement"], "a": 2,
      "e": "Il est strictement défendu à quiconque, en tout temps, de descendre au fond de la monterie pour récupérer des pièces." },
    { "q": "Que faut-il faire AVANT d'enlever le couvercle de la monterie ?",
      "o": ["Couper l'air", "Porter un harnais et s'attacher à un ancrage ou une ligne de vie", "Appeler le fournisseur", "Rien"], "a": 1,
      "e": "Porter un harnais et s'attacher à un ancrage ou à une ligne de vie avant d'enlever le couvercle (risque de chute)." },
    { "q": "Jusqu'à quand doit-on rester attaché ?",
      "o": ["Quelques secondes", "Tant que le couvercle est retiré de la monterie", "Jamais", "Seulement en montant"], "a": 1,
      "e": "Demeurer attaché durant tous les travaux de manipulation et tant que le couvercle est retiré." },
    { "q": "Avec quel outil récupère-t-on le taillant ou les pièces brisées au fond ?",
      "o": ["À la main", "Avec le racloir de monterie (raise scraper)", "Avec un aimant", "Avec une corde"], "a": 1,
      "e": "Récupérer uniquement à l'aide du racloir de monterie (raise scraper) conçu à cet effet." },
    { "q": "Que fait-on du couvercle entre les manipulations du racloir ?",
      "o": ["On le jette", "On le remet sur la monterie", "On le laisse ouvert", "On le perce"], "a": 1,
      "e": "Remettre le couvercle sur la monterie entre les manipulations du racloir." },
    { "q": "Quel est le principal danger quand le couvercle est ouvert ?",
      "o": ["Le bruit", "La chute dans la monterie (trou béant)", "La poussière", "Le froid"], "a": 1,
      "e": "Couvercle ouvert = trou béant : risque de chute dans la monterie." },
    { "q": "Que sort-on de la monterie avant d'entreprendre la récupération ?",
      "o": ["Le couvercle", "La V-30 (en enlevant les tiges de forage)", "Le racloir", "Rien"], "a": 1,
      "e": "Sortir la V-30 de la monterie en enlevant les tiges de forage avant de récupérer le taillant brisé." },
    { "q": "Si le taillant brisé reste et que l'accès inférieur est impossible, qui avise-t-on ?",
      "o": ["Le fournisseur", "Le superviseur de la mine", "Personne", "L'aide-foreur"], "a": 1,
      "e": "Avertir le superviseur de la mine lorsqu'un taillant brisé demeure et que l'accès n'est pas possible." }
  ],
  "pro-op-ith-012": [
    { "q": "Quelle distance minimale entre le foreur et le trou avec le système à distance ?",
      "o": ["10 pieds", "50 pieds (15 mètres)", "100 pieds", "5 mètres"], "a": 1,
      "e": "Installer le système de commande à distance à un minimum de 50' (15 mètres) entre le foreur et le trou." },
    { "q": "Où le foreur et l'aide-foreur ne doivent-ils JAMAIS se tenir ?",
      "o": ["Près de la sortie", "Dans la ligne de sautage", "Derrière une protection", "En zone sécuritaire"], "a": 1,
      "e": "Ne jamais se tenir dans la ligne de sautage; rester du côté de la sortie." },
    { "q": "Vers où doivent se positionner le foreur et l'aide-foreur ?",
      "o": ["Vers le fond", "Vers la sortie, sans rien qui bloque l'accès", "Vers le trou", "Au centre"], "a": 1,
      "e": "Se positionner vers la sortie en s'assurant que rien ne bloque l'accès." },
    { "q": "Comment protège-t-on les accès aux lieux de forage ?",
      "o": ["On les laisse ouverts", "Barricader avec signalisation (ACCÈS INTERDIT, FORAGE À DISTANCE)", "Avec un seul cône", "Avec une lampe"], "a": 1,
      "e": "Barricader tous les accès et apposer une signalisation (ACCÈS INTERDIT, FORAGE EN COURS, FORAGE À DISTANCE)." },
    { "q": "À quelle fréquence la procédure sur les barricades doit-elle être signée ?",
      "o": ["Une fois par mois", "Au début de chaque quart, avant le forage", "Jamais", "Une seule fois"], "a": 1,
      "e": "La procédure (dans un sac étanche) est signée par le foreur avant le début du forage, au début de chaque quart." },
    { "q": "Comment doit-on procéder pour toute visite des lieux de forage ?",
      "o": ["Y aller directement", "Contacter l'opérateur par radio d'abord", "Crier", "Attendre la fin du quart"], "a": 1,
      "e": "Contacter l'opérateur par radio; à défaut, le foreur se déplace vers les visiteurs si un contact visuel est possible." },
    { "q": "Dans quel état doit être la zone de forage pendant l'opération à distance ?",
      "o": ["Surveillée par un gardien", "Évacuée", "Éclairée seulement", "Peu importe"], "a": 1,
      "e": "S'assurer que la zone de forage est évacuée et que la foreuse est exécutée par commande à distance sous surveillance." },
    { "q": "Lors du déblocage, si on voit un explosif dans le matériel qui sort, que fait-on ?",
      "o": ["On continue", "On arrête l'opération avec la foreuse et on avise le superviseur", "On l'enlève à la main", "On l'arrose"], "a": 1,
      "e": "En cas de présence d'explosif, arrêter immédiatement l'opération avec la foreuse et aviser le superviseur." },
    { "q": "Pour débloquer un trou dynamité à l'amex (ANFO), que met-on dans les tiges ?",
      "o": ["De l'huile", "De l'eau (pour diminuer le risque d'explosion)", "De l'air", "Du sable"], "a": 1,
      "e": "Mettre de l'eau dans les tiges de forage pour diminuer le risque d'explosion lors du déblocage d'un trou à l'ANFO." },
    { "q": "Quel article du règlement encadre le forage à distance ?",
      "o": ["Article 100", "Article 440", "Article 250", "Article 12"], "a": 1,
      "e": "L'article 440 du Règlement sur la SST dans les mines permet de forer à moindre distance par commande à distance, zone évacuée." }
  ],
  "pro-op-ith-014": [
    { "q": "Quand est-il interdit de positionner une partie de son corps sous les tables ?",
      "o": ["Jamais interdit", "Si le marteau n'est pas monté au-delà des tables et la slip-plate pas fermée", "Seulement la nuit", "Si la foreuse tourne"], "a": 1,
      "e": "Interdit de mettre une partie du corps sous les tables si le marteau n'est pas monté au-delà des tables ET que la slip-plate n'est pas fermée." },
    { "q": "Quelle distance minimale obligatoire entre le mât et la console ?",
      "o": ["0,5 m", "1 m", "1,5 mètre", "3 m"], "a": 2,
      "e": "Une distance minimum de 1,5 mètre entre le mât et la console doit obligatoirement être respectée." },
    { "q": "Quand une pièce est en mouvement, où ne peut-on se placer ?",
      "o": ["Derrière la console", "Entre la console et le mât, ni à moins de 1,5 m du mât", "Près du tubage", "Au sol"], "a": 1,
      "e": "Aucun travailleur ne peut se placer entre la console et le mât, ni à moins de 1,5 m du mât de tous les côtés." },
    { "q": "Avant de procéder au nettoyage, que fait-on du marteau et de la slip-plate ?",
      "o": ["Rien", "Monter le marteau au-delà des tables, fermer la slip-plate, appuyer la bit et fermer l'interrupteur", "Baisser le marteau", "Ouvrir la slip-plate"], "a": 1,
      "e": "Monter le marteau au-delà des tables, fermer la slip-plate ou les jaws, appuyer la bit dessus et fermer l'interrupteur de la foreuse." },
    { "q": "Comment visse-t-on le marteau au saver sub ?",
      "o": ["Au complet sans le serrer avec force", "Le plus fort possible", "À moitié", "À la clé à choc"], "a": 0,
      "e": "Visser le marteau au saver sub au complet sans le serrer avec force." },
    { "q": "Pourquoi ne pas laisser les tubages dépasser trop longs du plancher ?",
      "o": ["Pour l'esthétique", "Ils deviennent des embûches; le trajet des travailleurs doit en être exempt", "Pour économiser", "Aucune raison"], "a": 1,
      "e": "Les tubages trop longs deviennent des embûches; le trajet des travailleurs doit être exempt de tubages qui dépassent." },
    { "q": "Pourquoi la longueur de dépassement des tubages peut-elle changer ?",
      "o": ["À cause du vent", "À cause de l'accumulation de boue de forage", "À cause du gel", "Elle ne change pas"], "a": 1,
      "e": "La longueur de dépassement peut changer pendant le forage à cause de l'accumulation de boue de forage." },
    { "q": "À quoi sert le tubage (casing) installé au collet du trou ?",
      "o": ["À décorer", "À protéger le collet contre la chute de roches qui bloquerait le trou", "À mesurer la profondeur", "À éclairer"], "a": 1,
      "e": "Le tubage protège le collet contre la chute de roches qui pourrait bloquer le trou et nuire au forage ou au chargement d'explosifs." },
    { "q": "Quelle procédure doit-on respecter au préalable, et que vérifier ?",
      "o": ["Aucune", "La procédure PRO-OP-ITH-004 et le bon alignement de la foreuse selon les plans", "Seulement le cadenassage", "PRO-MEC-011"], "a": 1,
      "e": "Respecter d'abord la procédure de forage PRO-OP-ITH-004 et s'assurer que la foreuse est bien alignée selon les plans." },
    { "q": "Au 2e forage, de combien le casing doit-il entrer dans le roc solide ?",
      "o": ["1 pouce", "1 pied", "3 pieds", "Il n'entre pas dans le roc"], "a": 1,
      "e": "Au 2e forage, le casing (4, 6 ou 10 pouces) doit entrer de 1 pied dans le roc solide." }
  ],
  "pro-op-ith-016": [
    { "q": "Comment transporte-t-on en tout temps les marteaux de 6\" ?",
      "o": ["À bras", "À l'aide du chariot conçu à cet effet", "Sur l'épaule", "En les roulant"], "a": 1,
      "e": "Transporter en tout temps les marteaux de 6\" à l'aide du chariot conçu à cet effet." },
    { "q": "Quel composant doit toujours être installé sur les marteaux lors de la manipulation ?",
      "o": ["Le Driver Sub", "Le Gear Box", "La slip-plate", "Le centralisateur"], "a": 0,
      "e": "Installer le « Driver Sub » sur les marteaux en tout temps lors de la manipulation." },
    { "q": "Comment installe-t-on les marteaux de 3\" et 4\" ?",
      "o": ["Au chariot uniquement", "Manuellement sur le Gear Box, comme les tiges (puis procédure à partir du point #8)", "À la grue", "On ne les installe pas"], "a": 1,
      "e": "Les marteaux de 3\" et 4\" s'installent manuellement sur le Gear Box comme les tiges, puis on applique la procédure à partir du point #8." },
    { "q": "Que faut-il valider chaque fois qu'on doit exposer les mains sous le marteau ?",
      "o": ["Que la radio fonctionne", "Que le marteau est bien vissé au Gear Box", "Que le chariot est propre", "Rien"], "a": 1,
      "e": "À chaque fois qu'on doit s'exposer les mains sous le marteau, valider que le marteau est bien vissé au Gear Box." },
    { "q": "Lors du dévissage manuel du marteau, que faut-il éviter ?",
      "o": ["Exposer les mains", "Utiliser le Driver Sub", "Communiquer", "Aller vite"], "a": 0,
      "e": "Ne pas s'exposer les mains lors du dévissage manuel du marteau." },
    { "q": "Quand retire-t-on la chaîne de sûreté du chariot ?",
      "o": ["Au début", "Seulement après avoir vissé et accoté le marteau dans le saver sub", "Jamais", "Avant de visser"], "a": 1,
      "e": "Retirer la chaîne de sûreté du chariot seulement après avoir vissé et accoté le marteau dans le saver sub." },
    { "q": "Que fait-on avant de sortir le chariot ?",
      "o": ["On part", "On attache le marteau avec la chaîne de retenue", "On enlève le Driver Sub", "On baisse la slip-plate"], "a": 1,
      "e": "Attacher le marteau à l'aide de la chaîne de retenue avant de sortir le chariot." },
    { "q": "Pourquoi respecter la séquence de travail établie ?",
      "o": ["Pour aller plus vite", "Pour éviter la chute d'un marteau et le développement de TMS", "Pour le bruit", "Aucune raison"], "a": 1,
      "e": "Respecter la séquence évite l'exposition à la chute d'un marteau et le développement de troubles musculo-squelettiques (TMS)." },
    { "q": "Combien pèse le marteau de 3\" ?",
      "o": ["60 lbs", "89 lbs", "211 lbs", "150 lbs"], "a": 0,
      "e": "Le marteau de 3\" pèse 60 lbs (4\" = 89 lbs, 6\" = 211 lbs)." },
    { "q": "Combien pèse le marteau de 6\" ?",
      "o": ["89 lbs", "150 lbs", "211 lbs", "60 lbs"], "a": 2,
      "e": "Le marteau de 6\" pèse 211 lbs : d'où l'obligation d'utiliser le chariot." },
    { "q": "À l'étape finale, de combien dévisse-t-on le marteau ?",
      "o": ["1 tour seulement", "5 tours", "Complètement", "Une demi-tour"], "a": 0,
      "e": "Le dévissage final du marteau (étape 29) est de 1 tour seulement." },
    { "q": "Que doit-on maintenir entre le foreur et l'aide-foreur durant la manipulation ?",
      "o": ["Le silence", "Une bonne communication", "Une distance de 7 m", "Un contact physique"], "a": 1,
      "e": "Maintenir une bonne communication entre le foreur et l'aide-foreur durant toute la manipulation." }
  ]
};
