/* ===========================================================================
   QUIZ — Nouvelles procédures secteur ITH (PRO-OP-ITH-017, bits CUBEX, PIPE-TUB,
   STOPEMASTER 001/002/003/004, foreuse V-KING). Citations fidèles des PDF.
   =========================================================================== */
(function () {
  var Q = {
    "pro-op-ith-017": [
      { "q": "Quand on déplace les tiges, à quelle distance doivent rester le soudeur et les travailleurs du haut ?",
        "o": ["1 mètre", "2 mètres", "3 mètres", "5 mètres"], "a": 2,
        "e": "« …doivent obligatoirement se tenir à une distance minimum de 3 mètres. »" },
      { "q": "Pour une cédule 80, quelle pression doit montrer le cadran des mâchoires hydrauliques ?",
        "o": ["2000 à 3000 psi", "8800 à 8900 psi", "5000 à 6000 psi", "1000 psi au maximum"], "a": 1,
        "e": "« La pression sur le cadran doit être entre 8800 psi et 8900 psi pour une cédule 80. »" },
      { "q": "Quel poids maximum peut soulever la foreuse CUBEX pour ce travail ?",
        "o": ["10 000 lbs", "15 000 lbs", "25 000 lbs", "40 000 lbs"], "a": 2,
        "e": "« La capacité maximale de l'équipement de forage (CUBEX) est de 25 000 lbs. Ce sont les ''SLIP PLATES'' qui déterminent ce maximum. »" },
      { "q": "Pendant le travail, qui a le droit de se parler ?",
        "o": ["Toute l'équipe", "Le foreur et le soudeur seulement, sans personne au milieu", "Le superviseur et le foreur", "N'importe qui, par radio"], "a": 1,
        "e": "« Les deux seules personnes à communiquer ensemble doivent être le foreur et le soudeur. Aucune personne ne doit faire l'intermédiaire. »" },
      { "q": "Quel poids au minimum doit tenir l'élingue qui soulève la charge ?",
        "o": ["500 kg", "Une tonne", "2 tonnes", "5 tonnes"], "a": 1,
        "e": "« L'élingue servant au levage de la charge doit avoir une capacité minimale d'une tonne et elle doit être accrochée à une plaque d'ancrage fixée au toit… »" }
    ],
    "pro-op-ith-001": [
      { "q": "Tu mets le SHANK dans le marteau. Ensuite, tu visses la bit d'au moins combien de tours ?",
        "o": ["Un demi-tour", "Au moins 2 tours", "5 tours", "Juste jusqu'au blocage"], "a": 1,
        "e": "« Aligner le SHANK dans le bout du marteau, l'insérer le plus loin possible et visser la bit un minimum de 2 tours. »" },
      { "q": "Avec quelle pression faut-il serrer la bit ?",
        "o": ["Entre 1000 et 2000 psi", "Entre 3000 et 4000 psi", "500 psi au maximum", "Plus de 5000 psi"], "a": 0,
        "e": "« Serrer la bit avec un minimum de 1000 psi et pas plus de 2000 psi. »" },
      { "q": "Avant de poser le driver sub, que fais-tu à ses filets ?",
        "o": ["Les nettoyer à l'air", "Bien les graisser", "Les chauffer", "Rien"], "a": 1,
        "e": "« Bien graisser les filets du driver sub. »" }
    ],
    "pro-pt-001": [
      { "q": "Le bras télescopique du PIPE-TUB mesure quelle longueur ?",
        "o": ["6 pi (1,8 m)", "12 pi (3,66 m)", "20 pi (6 m)", "8 pi (2,4 m)"], "a": 1,
        "e": "« …manipuler des tiges au train de forage au moyen d'un bras télescopique de 12 pi [3,66 m]. »" },
      { "q": "Pendant le forage, à quelle distance du mât place-t-on les contrôles ?",
        "o": ["Tout près", "À plus de 1,5 mètre du mât", "À 0,5 mètre", "Sur le mât"], "a": 1,
        "e": "« Positionner les contrôles à plus de 1,5 mètre du mât de la foreuse et à 1,5 mètre du bras collier. »" },
      { "q": "Tu n'utilises pas la commande à distance. Que fais-tu ?",
        "o": ["Rien", "Mettre la fiche d'obturation dans la boîte de connexion", "Débrancher la foreuse", "La laisser pendre"], "a": 1,
        "e": "« Si la commande à distance n'est pas utilisée, la fiche d'obturation doit être insérée dans la boîte de connexion. »" }
    ],
    "pro-op-sm-001": [
      { "q": "Tu trouves la zone de forage. Que vérifies-tu en premier ?",
        "o": ["L'éclairage", "L'air (la ventilation)", "Le niveau d'eau", "Les outils"], "a": 1,
        "e": "« Après avoir localisé la zone de forage, vérifiez d'abord la qualité de la ventilation. »" }
    ],
    "pro-op-sm-002": [
      { "q": "Les tiges tournent. Tu dois toujours rester à quelle distance ?",
        "o": ["1 mètre", "2,4 mètres", "5 mètres", "Pas de distance fixe"], "a": 1,
        "e": "« Tenez-vous toujours à l'écart (2,4 mètres) des tiges rotatives. »" },
      { "q": "Un trou a besoin de plusieurs forets. Dans quel ordre les utiliser ?",
        "o": ["Les plus usés d'abord", "Les neufs d'abord, puis les usés", "Peu importe", "Alterner neuf et usé"], "a": 1,
        "e": "« Si vous utilisez plus d'un foret dans un même trou : toujours utiliser les forets neufs au début en allant vers les plus usés. »" }    ],
    "pro-op-sm-003": [
      { "q": "Quand la foreuse se déplace, quelle distance minimum garder entre toi et elle ?",
        "o": ["1 mètre", "2,4 mètres", "5 mètres", "Aucune"], "a": 1,
        "e": "« Toujours garder une distance de 2,4 mètres minimum entre vous et la foreuse. »" },
      { "q": "Quand tu déplaces la machine dans la rampe, où doit être le panier ?",
        "o": ["Vers le bas", "Toujours vers le haut (UP RAMP)", "Au centre", "Replié"], "a": 1,
        "e": "« Lors des déplacements, le panier doit TOUJOURS être vers le haut (UP RAMP). »" },
      { "q": "Sur quels tuyaux faut-il mettre des câbles anti-fouet (whipcheck) ?",
        "o": ["Tous les tuyaux", "Les tuyaux de plus de 1 pouce", "Juste les tuyaux d'eau", "Aucun"], "a": 1,
        "e": "« Installer des câbles anti-fouets (whipcheck) sur les tuyaux de plus d'un (1) pouce. »" }
    ],
    "pro-op-sm-004": [
      { "q": "Au Québec, quel article du règlement (RSSTM) dit de souffler le plancher avant de forer ?",
        "o": ["Article 12", "Article 437", "Article 136", "Article 439"], "a": 1,
        "e": "« Le plancher du chantier à forer doit être soufflé selon l'article 437 du Règlement sur la santé et la sécurité du travail dans les mines (RSSTM Québec)… »" },
      { "q": "Le casing doit mesurer quelle longueur ?",
        "o": ["Aussi long que le trou", "Environ 2 pouces de plus que la partie alésée", "2 pieds de plus", "Peu importe"], "a": 1,
        "e": "« Retirez la tige et insérez un casing d'environ 2 pouces plus long que la longueur alésée. »" }
    ],
    "pro-op-bu-001": [
      { "q": "Quelle protection portes-tu toujours quand tu fais marcher la foreuse V-KING ?",
        "o": ["Un masque seulement", "Une double protection pour les oreilles", "Un harnais", "Rien de spécial"], "a": 1,
        "e": "« Le port de la double protection auditive est obligatoire. »" },
      { "q": "Tu forages un trou vers le bas. Quelle longueur de tubage mets-tu dans le roc, au moins ?",
        "o": ["6 pouces", "12 pouces", "24 pouces", "Aucune"], "a": 1,
        "e": "« Lors du forage de trous descendant, le foreur devra installer un tubage d'une longueur minimum de 12 pouces dans le roc. »" },
      { "q": "Quelles conduites d'air ont besoin d'un système anti-fouettement ?",
        "o": ["Toutes", "Les conduites souples de plus de 1 pouce", "Seulement les conduites d'eau", "Aucune"], "a": 1,
        "e": "« Toutes les conduites d'air flexibles supérieures à 1 pouce de diamètre doivent être équipées d'un dispositif anti-fouettement approprié et ce à tous les points de connexion. »" },
      { "q": "Un trou vers le bas est fini. Que mets-tu dessus ?",
        "o": ["Un cône", "Un bouchon, pour empêcher les pierres de tomber dans le trou", "Un drapeau", "Rien"], "a": 1,
        "e": "« Après chaque trou descendant complété, l'opérateur installera des bouchons sur chacun des trous afin d'empêcher la chute de pierre ou de débris qui pourrait entraîner un blocage du trou. »" }
    ],
    "pro-mec-001": [
      { "q": "Quelle capacité minimale doit avoir l'équipement de levage pour démonter le mât ?",
        "o": ["3 000 livres", "6 000 livres", "10 000 livres", "15 000 livres"], "a": 1,
        "e": "« Équipement de levage doit avoir une capacité de 6,000 livres ou plus. »" },
      { "q": "À quelle distance minimale de la foreuse dois-tu te tenir avant le retrait du mât ?",
        "o": ["6 pieds", "8 pieds", "10 pieds", "12 pieds"], "a": 3,
        "e": "« Se tenir dans un endroit sécuritaire d'une distance minimum de douze pieds de la foreuse… »" },
      { "q": "Où ne dois-tu JAMAIS te placer pendant l'opération ?",
        "o": ["Devant la foreuse", "En-dessous du mât", "Derrière l'opérateur", "Sur le châssis"], "a": 1,
        "e": "« TRÈS IMPORTANT : NE JAMAIS SE PLACER EN-DESSOUS DU MAT. »" },
      { "q": "Quel diamètre doit avoir la manille (clavis) reliant les élingues ?",
        "o": ["1/2 pouce", "3/4 pouce", "1 pouce", "2 pouces"], "a": 2,
        "e": "« …reliées entre elles par le centre avec une grosse manille (clavis) d'un pouce de diamètre. »" }
    ],
    "pro-mec-002": [
      { "q": "À quel couple serres-tu les boulons SECS du mât ?",
        "o": ["80 lbs/pied", "95 lbs/pied", "110 lbs/pied", "150 lbs/pied"], "a": 2,
        "e": "« Boulons secs……………………110 lbs/pied »" },
      { "q": "Et les boulons LUBRIFIÉS (anti-seize) ?",
        "o": ["60 lbs/pied", "80 lbs/pied", "100 lbs/pied", "110 lbs/pied"], "a": 1,
        "e": "« Boulons lubrifiés (anti-seize)…..80 lbs/pied »" },
      { "q": "Combien de boulons faut-il installer sur le mât ?",
        "o": ["8", "10", "12", "14"], "a": 2,
        "e": "« Installer les douze boulons en suivant la séquence ci-dessous. »" },
      { "q": "Quand peux-tu retirer les élingues ?",
        "o": ["Dès que le mât touche l'actuateur", "Seulement quand les boulons sont bien serrés", "Avant de démarrer la foreuse", "Après le premier boulon"], "a": 1,
        "e": "« Retirer les élingues seulement quand les boulons sont bien serrés. »" }
    ],
    "pro-mec-003": [
      { "q": "À quel angle places-tu le mât avant de commencer ?",
        "o": ["45 degrés", "60 degrés", "90 degrés", "0 degré (horizontal)"], "a": 2,
        "e": "« Mettre le mât à 90 degrés »" },
      { "q": "À quel couple serres-tu la swivel à la fin ?",
        "o": ["400 lbs", "600 lbs", "800 lbs", "1000 lbs"], "a": 2,
        "e": "« Terminer par le serrage de la swivel à (800 lbs de torque). »" },
      { "q": "Avant de retirer les deux derniers boulons du gear box, que fais-tu ?",
        "o": ["Rien de spécial", "Une légère tension sur les élingues ou les fourches", "Tu le soulèves complètement", "Tu le laisses tomber"], "a": 1,
        "e": "« Appuyer les fourches sous le gear box ou mettre une légère tension sur les élingues ou la chaîne »" },
      { "q": "Une fois le nouveau gear box en place, que dois-tu vérifier ?",
        "o": ["Sa couleur", "Qu'il tourne dans le bon sens", "Son poids", "Rien"], "a": 1,
        "e": "« S'assurer que le gear box tourne dans le bon sens. »" }
    ],
    "pro-mec-004": [
      { "q": "Que dois-tu cadenasser avant de dévisser les boyaux à air ?",
        "o": ["Rien", "L'air au header (alimentation principale)", "Seulement l'eau", "Le moteur électrique"], "a": 1,
        "e": "« Cadenasser l'air au header (alimentation principale) et purger l'air sur la foreuse »" },
      { "q": "Peux-tu tenir la swivel avec les mains pendant que la rotation est actionnée ?",
        "o": ["Oui, toujours", "Oui, avec des gants", "Non, jamais", "Seulement à basse vitesse"], "a": 2,
        "e": "« NE JAMAIS TENIR LA SWIVEL AVEC LES MAINS QUAND LA ROTATION EST ACTIONNÉE. »" },
      { "q": "Quelle pression maximale ne dois-tu pas dépasser sur le cadran de rotation ?",
        "o": ["500 PSI", "800 PSI", "1000 PSI", "1200 PSI"], "a": 1,
        "e": "« NE PAS DÉPASSER 800 PSI sur le cadran de rotation. »" },
      { "q": "Dans quel sens sont les filets de la swivel ?",
        "o": ["Horaires", "Anti-horaires", "Ça dépend du modèle", "Il n'y a pas de filets"], "a": 1,
        "e": "« …dévisser la swivel à la main (les filets sont anti-horaires). »" }
    ],
    "pro-mec-005": [
      { "q": "Que ne dois-tu JAMAIS faire pendant les opérations de levage et d'élingage ?",
        "o": ["Porter des gants", "Te positionner sous une charge", "Parler à l'opérateur", "Utiliser des élingues"], "a": 1,
        "e": "« NE JAMAIS SE POSITIONNER SOUS UNE CHARGE PENDANT LES OPÉRATIONS DE LEVAGE ET D'ÉLINGAGE »" },
      { "q": "Quelle procédure dois-tu appliquer en premier pour enlever le mât ?",
        "o": ["PRO-MEC-002", "PRO-MEC-001", "PRO-MEC-005 elle-même", "Aucune, tu improvises"], "a": 1,
        "e": "« La procédure PRO-MEC-001 Démantèlement du mât doit être appliquée pour enlever le mât »" },
      { "q": "Qui doit déconnecter le moteur électrique ?",
        "o": ["N'importe quel travailleur", "Un électricien", "Le foreur", "Le mécanicien de garde"], "a": 1,
        "e": "« Un électricien doit déconnecter le moteur électrique; »" },
      { "q": "Qui est responsable de l'élingage dans le puits et des déplacements en galerie ?",
        "o": ["Machines Roger International", "La mine", "L'opérateur de la CUBEX", "Le fournisseur d'équipement"], "a": 1,
        "e": "« Les déplacements dans la galerie sont la responsabilité de la mine. L'élingage dans le puits est la responsabilité de la mine. »" }
    ],
    "pro-mec-006": [
      { "q": "Dans la méthode 1, que ne dois-tu PAS faire avec la tige de forage ?",
        "o": ["La visser au saver sub", "La lubrifier", "La retirer", "La mesurer"], "a": 0,
        "e": "« NE PAS VISSER LA TIGE AU SAVER SUB »" },
      { "q": "À quelle pression hydraulique visses-tu complètement le nouveau saver sub ?",
        "o": ["1 500 psi", "2 000 psi", "2 800 psi", "3 500 psi"], "a": 2,
        "e": "« …préalablement ajustée à 2800 psi, pour visser complètement le saver sub… »" },
      { "q": "Dans la méthode 2, que faut-il éviter en repositionnant la clé ?",
        "o": ["De la salir", "Une zone de coincement", "De la faire tomber", "Rien de particulier"], "a": 1,
        "e": "« …il faut la manipuler par l'extrémité afin de ne pas s'exposer à une zone de coincement. (Cercle jaune) »" },
      { "q": "Sur la nouvelle console, que dois-tu faire avant d'entretenir une composante du mât ?",
        "o": ["Rien de spécial", "Enfoncer le bouton d'arrêt", "Mettre le levier au maximum", "Débrancher la radio"], "a": 1,
        "e": "« …il doit obligatoirement enfoncer le bouton d'arrêt pour enlever l'alimentation de la console. »" }
    ],
    "pro-mec-007": [
      { "q": "Combien de côtés de la foreuse peux-tu soulever en même temps ?",
        "o": ["Les deux", "Un seul", "Aucun, tout reste au sol", "Ça dépend du poids"], "a": 1,
        "e": "« Il est strictement interdit de soulever l'ensemble de la foreuse d'un seul coup. »" },
      { "q": "Sur quelle structure ne peux-tu PAS appuyer le blocage de bois ?",
        "o": ["Le châssis", "Le panier", "Les chenilles", "La table"], "a": 1,
        "e": "« Mise en garde : La structure du panier n'est pas un point d'appui pour le blocage »" },
      { "q": "Quelle est la hauteur maximale pour lever un côté de la foreuse ?",
        "o": ["10 cm (4'')", "20 cm (8'')", "30 cm (12'')", "50 cm (20'')"], "a": 1,
        "e": "« Monter la foreuse de maximum 20 cm (8'') en utilisant la poussée hydraulique du mât… »" },
      { "q": "Combien pèse une foreuse CUBEX, selon cette procédure ?",
        "o": ["15 000 lbs", "18 000 lbs", "22 000 lbs", "30 000 lbs"], "a": 2,
        "e": "« Le poids d'une Cubex est 22000 Lbs »" }
    ],
    "pro-mec-008": [
      { "q": "Combien de côtés du système de glissière changes-tu à la fois ?",
        "o": ["Les deux en même temps", "Un seul à la fois", "Aucun ordre précis", "Trois"], "a": 1,
        "e": "« N.B. ne faire qu'une seule partie à la fois et un seul côté à la fois. »" },
      { "q": "En atelier, quelle capacité minimale doit avoir l'élingue utilisée avec le pont roulant ?",
        "o": ["3 000 livres", "5 000 livres", "7 000 livres", "10 000 livres"], "a": 2,
        "e": "« Utiliser une élingue d'une capacité de 7000 livres. »" },
      { "q": "En chantier, quelle longueur minimale de tige forés-tu dans le roc pour immobiliser la tête de rotation ?",
        "o": ["1 mètre", "1,8 m", "2,5 m", "3 m"], "a": 1,
        "e": "« Forer la longueur du marteau et une tige de 1.8 m dans le roc. »" },
      { "q": "Quels outils sont requis pour cette procédure ?",
        "o": ["Clé 15/16'' et clé 3/4''", "Marteau seulement", "Perceuse", "Aucun outil"], "a": 0,
        "e": "« Clé 15/16'' • Ratchet et Douille 15/16'' • Clé ¾ »" }
    ],
    "pro-mec-009": [
      { "q": "Combien de boulons de floating box dévisses-tu au départ ?",
        "o": ["4", "6", "8", "10"], "a": 2,
        "e": "« Dévisser à moitié les 8 boulons de floating box »" },
      { "q": "Combien de personnes doivent donner des indications à l'opérateur de l'équipement de levage ?",
        "o": ["Une seule", "Deux", "Toute l'équipe", "Le superviseur et le foreur"], "a": 0,
        "e": "« À ce stade, une seule personne doit donner des indications à l'opérateur de l'équipement de levage »" },
      { "q": "Comment installes-tu l'élingue autour du cylindre à retirer ?",
        "o": ["En panier", "En choke", "Nouée simplement", "Avec deux crochets"], "a": 1,
        "e": "« Installer une élingue de 4 ou 6 pieds en CHOKE autour du cylindre le plus près possible à gauche du gear box. »" },
      { "q": "En dévissant les bouchons de la grosse canisse à la fin, à quoi dois-tu faire attention ?",
        "o": ["À la température", "À la pression accumulée", "Au bruit", "À rien de particulier"], "a": 1,
        "e": "« …porter une attention particulière à la pression accumulée. Dévisser lentement. »" }
    ],
    "pro-mec-010": [
      { "q": "Combien de boulons faut-il retirer/serrer sur l'actuateur ?",
        "o": ["8", "10", "12", "14"], "a": 2,
        "e": "« Procéder à l'enlèvement des 12 boulons d'actuateur… »" },
      { "q": "Où ne dois-tu JAMAIS te placer en retirant le mât ?",
        "o": ["Devant la foreuse", "En-dessous du mât", "À côté de l'opérateur", "Sur le châssis"], "a": 1,
        "e": "« TRÈS IMPORTANT : NE JAMAIS SE PLACER EN-DESSOUS DU MAT »" },
      { "q": "Après combien de temps de forage dois-tu resserrer les boulons de l'actuateur ?",
        "o": ["Immédiatement seulement", "Après 1 quart de travail", "Après une semaine", "Jamais"], "a": 1,
        "e": "« VEUILLEZ NOTER QUE LES BOULONS DEVRONT ÊTRE RESERRÉS APRÈS 1 QUART DE TRAVAIL DE FORAGE »" },
      { "q": "Que dois-tu appliquer sur les contrôles de la foreuse après le changement ?",
        "o": ["Rien", "Une étiquette bleue de suivi mécanique", "Un autocollant rouge", "Un cadenas permanent"], "a": 1,
        "e": "« APPLIQUER UNE ÉTIQUETTE BLEUE DE SUIVI MÉCANIQUE SUR LES CONTRÔLES DE LA FOREUSE »" }
    ]
  };
  var T = window.QUIZ_PROC || (window.QUIZ_PROC = {});
  Object.keys(Q).forEach(function (id) { T[id] = (T[id] || []).concat(Q[id]); });
})();
